---

- name: Create database
  postgresql_db:
    name: "{{ item.value.name }}"
    encoding: UTF-8
    owner: "{{ item.value.owner }}"
  become: true
  become_user: postgres
  when: postgresql.databases is defined
  with_dict: "{{ postgresql.databases }}"

- name: Create extensions
  postgresql_ext: name={{ item.name }} db={{ item.database }}
  become: true
  become_user: postgres
  when: postgresql.extensions is defined
  with_items: "{{ postgresql.extensions }}"
