---

- name: Create schema for postgresql exporter
  postgresql_schema:
    name: "{{ postgresql.exporter.schema }}"
    owner: "{{ postgresql.exporter.user }}"

- name: Create view for pg_stat_activity
  postgresql_query:
    query: "CREATE OR REPLACE VIEW {{ postgresql.exporter.schema }}.pg_stat_activity AS SELECT * FROM pg_catalog.pg_stat_activity;"

- name: Grant access
  postgresql_query:
    query: "GRANT SELECT ON {{ postgresql.exporter.schema }}.pg_stat_activity TO {{ postgresql.exporter.user }}"

- name: Create view for pg_stat_replication
  postgresql_query:
    query: "CREATE OR REPLACE VIEW {{ postgresql.exporter.schema }}.pg_stat_replication AS SELECT * FROM pg_catalog.pg_stat_replication"

- name: Grant access
  postgresql_query:
    query: "GRANT SELECT ON {{ postgresql.exporter.schema }}.pg_stat_replication TO {{ postgresql.exporter.user }};"

- name: Prepare folder
  file: path={{ postgresql.service_dir }} state=directory

- name: Assemble service config
  template:
    src: "{{ item }}.j2"
    dest: "{{ postgresql.service_dir }}/{{ item }}"
  with_items:
    - .env
    - docker-compose.yml
    - queries.yaml
  notify: restart postgresql service
