---

- name: Restart postgresql server
  systemd: name=postgresql state=restarted
  listen: restart postgresql server

- name: Restart postgresql service
  command: docker-compose up -d
  args:
    chdir: "{{ consul_dir }}"
  listen: restart postgresql service

- name: Update consul config  # noqa 305
  shell: docker kill -s HUP "{{ consul.container.name }}"
  listen: reload consul
